#!/usr/bin/env python
#-*- coding: utf-8 -*-
def factor(num):
	import math
	l = []
	if (num%2 == 0):
		i = 2
		while(i <= num/2):
			if (math.floor(num/float(i)) == (num/float(i))):
				if ((i * (num/i)) == num):
					l.append(str(i) + "*" + str(num/i))
					break
			if ((i-1) > (num/i)):
				break
			i += 1
	else:
		i = 3
		while(i <= num/2):
			if (math.floor(num/float(i)) == (num/float(i))):
				if ((i * (num/i)) == num):
					l.append(str(i) + "*" + str(num/i))
					break
			if ((i-1) > (num/i)):
				break
			i += 2
	return l
